export const routerLinks = {
    HOME:'/',
    SHOP:'/shop',
    CONTACT:'/contact',
    DETAIL:'/shop/shop-details/:id',
    CART: '/shop/shopping-cart',
    CHECKOUT: '/shop/checkout',
    LOGIN: '/login',
    REGISTRATION: '/registration',
    ADMIN: '/admin',
    CATEGORIES: '/admin/categories',
    PRODUCTS: '/admin/products',
    NOTIFICATIONS: '/admin/notifications',
    SETTINGS: '/admin/settings',
}